import { useState, useEffect, useRef } from "react";
import readNDJSONStream from "ndjson-readablestream";
import styles from "./EmployeePortal.module.css";
import { toggleTheme, getTheme, Theme } from "../../theme";
import { Table } from "../../components/ui";
import type { PermittedCategory, MyProfile, DocFile, Verification, ChatMessage, AssignedHearing } from "./types";
import { streamChatAnswer, exportAnswerToWord } from "../../services/chat";
import { useMyProfile, useMyDocuments, useChangePassword } from "../../hooks/useEmployeeProfile";
import { useMyHearings, useUpdateHearingOutcome } from "../../hooks/useAssignments";
import { useLogout } from "../../hooks/useAuth";

// ── Types ─────────────────────────────────────────────────────────────────────

type Panel = "chat" | "documents" | "assignments" | "profile";

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmtBytes(b: number): string {
    if (b >= 1_048_576) return `${(b / 1_048_576).toFixed(1)} MB`;
    if (b >= 1024)      return `${Math.round(b / 1024)} KB`;
    return `${b} B`;
}

function fmtDate(iso: string): string {
    return iso ? iso.slice(0, 10) : "—";
}

// Detect case law citations by filename pattern (PLD, SCMR, MLD, CLC prefixes)
const CASE_LAW_RE = /^(PLD|SCMR|MLD|CLC)[-_\s]/i;
function isCaseLawCitation(citation: string): boolean {
    return CASE_LAW_RE.test(citation.trim());
}

// ── Theme Toggle ──────────────────────────────────────────────────────────────

const ThemeToggle = () => {
    const [theme, setTheme] = useState<Theme>(getTheme());
    const handle = () => { const next = toggleTheme(); setTheme(next); };
    return <button className={styles.themeToggle} onClick={handle}>{theme === "dark" ? "Light Mode" : "Dark Mode"}</button>;
};

// ── Chat Panel ────────────────────────────────────────────────────────────────

const EXAMPLES = [
    "What are the key clauses in this contract?",
    "Summarise the main obligations",
    "Are there any penalty clauses?",
    "What is the notice period mentioned?",
];

// ── Export helpers ────────────────────────────────────────────────────────────

function exportToPDF(question: string, answer: string, citations: string[], orgName: string): void {
    const citHtml = citations.length > 0
        ? `<div class="section-label">Sources</div>
           <ol class="citations">${citations.map(c => `<li>${c}</li>`).join("")}</ol>`
        : "";
    const questionHtml = question
        ? `<div class="section-label">Question</div>
           <p class="question-text">${question.replace(/</g, "&lt;")}</p>`
        : "";
    const answerHtml = answer
        .split("\n")
        .filter(l => l.trim())
        .map(l => `<p>${l.replace(/</g, "&lt;")}</p>`)
        .join("");
    const now = new Date().toLocaleDateString("en-PK", { day: "numeric", month: "long", year: "numeric" });

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Project Ease Export</title>
<style>
  body { font-family: Georgia, serif; max-width: 740px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }
  .brand { text-align: center; margin-bottom: 1.5rem; border-bottom: 2px solid #b8964c; padding-bottom: 1rem; }
  .brand h1 { color: #b8964c; font-size: 1.5rem; margin: 0 0 0.25rem; }
  .brand p { color: #888; font-size: 0.8rem; margin: 0; }
  .section-label { font-size: 0.75rem; font-weight: bold; text-transform: uppercase; letter-spacing: 0.08em; color: #b8964c; margin: 1.5rem 0 0.4rem; }
  .question-text { font-style: italic; background: #f8f6f0; border-left: 3px solid #b8964c; padding: 0.6rem 1rem; margin: 0; }
  p { line-height: 1.7; margin: 0.5rem 0; }
  .citations { color: #444; font-size: 0.9rem; padding-left: 1.2rem; }
  .citations li { margin-bottom: 0.25rem; }
  .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #ddd; text-align: center; font-size: 0.75rem; color: #aaa; font-style: italic; }
  @media print { body { padding: 0; } }
</style>
</head><body>
<div class="brand">
  <h1>${orgName}</h1>
  <p>AI Research Export — Project Ease &nbsp;·&nbsp; ${now}</p>
</div>
${questionHtml}
<div class="section-label">Answer</div>
${answerHtml}
${citHtml}
<div class="footer">Generated by Project Ease · AI answers should be verified by a qualified lawyer.</div>
</body></html>`;

    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 400);
}

async function exportToWord(
    question: string,
    answer: string,
    citations: string[],
    orgName: string,
    setExporting: (v: boolean) => void
): Promise<void> {
    setExporting(true);
    try {
        const { blob, filename } = await exportAnswerToWord({ question, answer, citations, org_name: orgName });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    } catch (e) {
        alert(e instanceof Error ? e.message : "Network error. Please try again.");
    } finally {
        setExporting(false);
    }
}

// ── Urdu / RTL helpers ────────────────────────────────────────────────────────

/** True when the string contains at least one Urdu/Arabic script character. */
function containsUrdu(text: string): boolean {
    return /[؀-ۿݐ-ݿﭐ-﷿ﹰ-﻿]/.test(text);
}

/** System-prompt injection for Urdu mode (uses >>> prefix for injected_prompt). */
const URDU_PROMPT_OVERRIDE =
    ">>>اردو میں جواب دیں۔ پاکستانی عدالتوں اور قانونی ضروریات کے لیے رسمی اردو زبان استعمال کریں۔ " +
    "جوابات نستعلیق رسم الخط میں لکھیں۔";

// ─────────────────────────────────────────────────────────────────────────────

const ChatPanel = ({ orgName, categories }: { orgName: string; categories: PermittedCategory[] }) => {
    const [messages,      setMessages]      = useState<ChatMessage[]>([]);
    const [streamText,    setStreamText]    = useState("");
    const [input,         setInput]         = useState("");
    const [loading,       setLoading]       = useState(false);
    const [error,         setError]         = useState<string | null>(null);
    const [exportingIdx,  setExportingIdx]  = useState<number | null>(null);
    const [lang,          setLang]          = useState<"en" | "ur">("en");
    const abortRef  = useRef<AbortController | null>(null);
    const anchorRef = useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        anchorRef.current?.scrollIntoView({ behavior: "smooth" });
    }, [messages, streamText]);

    const send = async (question: string) => {
        const q = question.trim();
        if (!q || loading) return;
        setInput("");
        setError(null);

        const userMsg: ChatMessage = { role: "user", content: q };
        const history = [...messages, userMsg];
        setMessages(history);
        setLoading(true);
        setStreamText("");

        const ctrl = new AbortController();
        abortRef.current = ctrl;

        try {
            const res = await streamChatAnswer({
                messages: history.map(m => ({ role: m.role, content: m.content })),
                context: {
                    overrides: {
                        retrieval_mode:   "hybrid",
                        semantic_ranker:  true,
                        top:              5,
                        suggest_followup_questions: false,
                        ...(lang === "ur" ? { prompt_template: URDU_PROMPT_OVERRIDE } : {}),
                    }
                },
                session_state: null,
            }, ctrl.signal);

            let fullText     = "";
            let citations: string[] = [];
            let verification: Verification | undefined;

            for await (const event of readNDJSONStream(res.body!)) {
                if (ctrl.signal.aborted) break;
                if (event.type === "response.context" && event.context?.data_points) {
                    citations = event.context.data_points.citations ?? [];
                } else if (event.type === "response.output_text.delta" && event.delta !== undefined) {
                    setLoading(false);
                    fullText += event.delta;
                    setStreamText(fullText);
                } else if (event.type === "response.verification" && event.verification) {
                    verification = event.verification as Verification;
                } else if (event.error) {
                    throw new Error(event.error);
                }
            }

            const assistantMsg: ChatMessage = { role: "assistant", content: fullText, citations, verification };
            setMessages([...history, assistantMsg]);
            setStreamText("");
        } catch (e: any) {
            if (e?.name !== "AbortError") {
                setError(e?.message ?? "Something went wrong. Please try again.");
            }
        } finally {
            setLoading(false);
            setStreamText("");
            abortRef.current = null;
        }
    };

    const onKey = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(input); }
    };

    const stop = () => { abortRef.current?.abort(); };

    const clear = () => {
        abortRef.current?.abort();
        setMessages([]);
        setStreamText("");
        setError(null);
        setInput("");
    };

    const isEmpty = messages.length === 0 && !loading;

    return (
        <div className={styles.chatShell}>
            <div className={styles.chatMessages}>
                {isEmpty ? (
                    <div className={styles.emptyState}>
                        <div className={styles.emptyIcon}>💬</div>
                        <div className={styles.emptyTitle}>Ask anything about your documents</div>
                        <div className={styles.emptySub}>
                            {categories.length > 0
                                ? `You have access to: ${categories.map(c => c.name).join(", ")}.`
                                : "Your manager hasn't granted access to any document categories yet."}
                        </div>
                        {categories.length > 0 && (
                            <div className={styles.exampleGrid}>
                                {EXAMPLES.map(ex => (
                                    <button key={ex} className={styles.exampleBtn} onClick={() => send(ex)}>
                                        {ex}
                                    </button>
                                ))}
                            </div>
                        )}
                    </div>
                ) : (
                    <>
                        {messages.map((msg, i) => {
                            // Find the preceding user question for this assistant answer
                            const prevUserMsg = msg.role === "assistant" && i > 0 && messages[i - 1].role === "user"
                                ? messages[i - 1].content
                                : "";
                            const isUrduMsg = containsUrdu(msg.content);
                            return (
                                <div key={i} className={`${styles.msgRow} ${msg.role === "user" ? styles.msgRowUser : styles.msgRowAssistant}`}>
                                    <div className={`${styles.msgBubble} ${msg.role === "user" ? styles.msgBubbleUser : styles.msgBubbleAssistant}${isUrduMsg ? " urduText" : ""}`}
                                         dir={isUrduMsg ? "rtl" : undefined}>
                                        {msg.content}
                                    </div>
                                    {msg.role === "assistant" && msg.citations && msg.citations.length > 0 && (
                                        <div className={styles.msgCitations}>
                                            {msg.citations.map(c => (
                                                isCaseLawCitation(c) ? (
                                                    <span key={c} className={styles.citationTagCaseLaw} title="Case Law — PLD / SCMR / MLD / CLC">
                                                        📖 {c}
                                                    </span>
                                                ) : (
                                                    <span key={c} className={styles.citationTag}>📁 {c}</span>
                                                )
                                            ))}
                                        </div>
                                    )}
                                    {msg.role === "assistant" && msg.verification && (
                                        <div className={`${styles.verificationBadge} ${styles[`verdict_${msg.verification.verdict}`]}`}>
                                            {msg.verification.verdict === "verified"   && "✓ Verified against sources"}
                                            {msg.verification.verdict === "warning"    && "⚠ Partially verified"}
                                            {msg.verification.verdict === "unverified" && "✗ Could not verify"}
                                            {msg.verification.issues.length > 0 && (
                                                <span className={styles.verificationIssues}>
                                                    {" — "}{msg.verification.issues[0]}
                                                </span>
                                            )}
                                        </div>
                                    )}
                                    {msg.role === "assistant" && msg.content && (
                                        <div className={styles.exportBar}>
                                            <button
                                                className={styles.exportBtn}
                                                title="Export as PDF"
                                                onClick={() => exportToPDF(prevUserMsg, msg.content, msg.citations ?? [], orgName)}
                                            >
                                                ↓ PDF
                                            </button>
                                            <button
                                                className={styles.exportBtn}
                                                title="Export as Word document"
                                                disabled={exportingIdx === i}
                                                onClick={() => {
                                                    setExportingIdx(i);
                                                    exportToWord(
                                                        prevUserMsg,
                                                        msg.content,
                                                        msg.citations ?? [],
                                                        orgName,
                                                        (v) => { if (!v) setExportingIdx(null); }
                                                    );
                                                }}
                                            >
                                                {exportingIdx === i ? "…" : "↓ Word"}
                                            </button>
                                        </div>
                                    )}
                                </div>
                            );
                        })}

                        {/* Streaming in-progress */}
                        {(loading || streamText) && (
                            <div className={`${styles.msgRow} ${styles.msgRowAssistant}`}>
                                <div className={`${styles.msgBubble} ${styles.msgBubbleAssistant}`}>
                                    {streamText || <span style={{ color: "var(--text-3)" }}>Searching your documents…</span>}
                                    {(loading || streamText) && <span className={styles.streamingDot} />}
                                </div>
                            </div>
                        )}

                        {error && (
                            <div style={{ color: "#e05260", fontSize: "0.85rem", padding: "0.5rem" }}>
                                ⚠ {error}
                            </div>
                        )}
                    </>
                )}
                <div ref={anchorRef} className={styles.chatScrollAnchor} />
            </div>

            <div className={styles.chatInputBar}>
                {/* Language toggle */}
                <div className={styles.langToggleRow}>
                    <span className={styles.langToggleLabel}>Language:</span>
                    <button
                        className={lang === "en" ? styles.langBtnActive : styles.langBtn}
                        onClick={() => setLang("en")}
                    >EN</button>
                    <button
                        className={lang === "ur" ? styles.langBtnActive : styles.langBtn}
                        onClick={() => setLang("ur")}
                        title="اردو میں جواب حاصل کریں"
                    >اردو</button>
                    {lang === "ur" && (
                        <span className={styles.urduHint}>AI اردو میں جواب دے گا</span>
                    )}
                </div>

                <div className={styles.chatInputRow}>
                    <textarea
                        className={`${styles.chatInput}${lang === "ur" ? " urduInput" : ""}`}
                        value={input}
                        onChange={e => setInput(e.target.value)}
                        onKeyDown={onKey}
                        placeholder={lang === "ur" ? "اپنا سوال لکھیں…" : "Ask a question about your documents…"}
                        dir={lang === "ur" ? "rtl" : undefined}
                        rows={1}
                        disabled={loading && !streamText}
                    />
                    {loading || streamText ? (
                        <button className={styles.sendBtn} onClick={stop}>Stop</button>
                    ) : (
                        <button className={styles.sendBtn} onClick={() => send(input)} disabled={!input.trim()}>
                            {lang === "ur" ? "پوچھیں" : "Ask"}
                        </button>
                    )}
                </div>
                {messages.length > 0 && (
                    <div className={styles.chatHint}>
                        Press Enter to send · Shift+Enter for new line ·{" "}
                        <button
                            onClick={clear}
                            style={{ background: "none", border: "none", color: "var(--gold)", cursor: "pointer", fontSize: "inherit", padding: 0 }}
                        >
                            Clear chat
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

// ── Documents Panel ───────────────────────────────────────────────────────────

const DocumentsPanel = ({ docs }: { docs: DocFile[] }) => (
    <div className={styles.panelContent}>
        <Table empty={docs.length === 0}
            emptyMessage="No documents are accessible to you yet. Ask your manager to assign category permissions.">
            <thead>
                <tr>
                    <th>Document</th>
                    <th>Category</th>
                    <th>Size</th>
                    <th>Uploaded</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {docs.map(doc => (
                    <tr key={doc.doc_id}>
                        <td><span className={styles.docName}>{doc.filename}</span></td>
                        <td>
                            {doc.category_name
                                ? <span className={styles.catBadge}>{doc.category_name}</span>
                                : <span style={{ color: "var(--text-3)" }}>—</span>}
                        </td>
                        <td style={{ color: "var(--text-3)" }}>{fmtBytes(doc.size_bytes ?? 0)}</td>
                        <td style={{ color: "var(--text-3)" }}>{fmtDate(doc.uploaded_at ?? "")}</td>
                        <td>
                            {doc.status === "ready"      && <span className={styles.statusReady}>Ready</span>}
                            {doc.status === "processing" && <span className={styles.statusProc}>Processing…</span>}
                            {doc.status === "error"      && <span className={styles.statusError}>Error</span>}
                        </td>
                    </tr>
                ))}
            </tbody>
        </Table>
    </div>
);

// ── Profile Panel ─────────────────────────────────────────────────────────────

const ProfilePanel = ({ profile }: { profile: MyProfile }) => {
    const [currentPw,  setCurrentPw]  = useState("");
    const [newPw,      setNewPw]      = useState("");
    const [confirmPw,  setConfirmPw]  = useState("");
    const [pwError,    setPwError]    = useState<string | null>(null);
    const [pwSuccess,  setPwSuccess]  = useState(false);
    const changePw = useChangePassword();

    const changePassword = () => {
        setPwError(null);
        setPwSuccess(false);
        if (!currentPw || !newPw || !confirmPw) { setPwError("Please fill in all fields."); return; }
        if (newPw.length < 8) { setPwError("New password must be at least 8 characters."); return; }
        if (newPw !== confirmPw) { setPwError("New passwords do not match."); return; }
        changePw.mutate({ current_password: currentPw, new_password: newPw }, {
            onSuccess: () => {
                setPwSuccess(true);
                setCurrentPw(""); setNewPw(""); setConfirmPw("");
            },
            onError: (e: Error) => setPwError(e.message || "Could not change password."),
        });
    };

    return (
        <div className={styles.panelContent}>
            <div className={styles.profileGrid}>
                <div className={styles.profileCard}>
                    <div className={styles.profileCardTitle}>Your Account</div>
                    <div className={styles.profileRow}>
                        <span className={styles.profileLabel}>Full Name</span>
                        <span className={styles.profileValue}>{profile.name}</span>
                    </div>
                    <div className={styles.profileRow}>
                        <span className={styles.profileLabel}>Email</span>
                        <span className={styles.profileValue}>{profile.email}</span>
                    </div>
                    <div className={styles.profileRow}>
                        <span className={styles.profileLabel}>Role</span>
                        <span className={styles.profileValue}>Employee</span>
                    </div>
                    <div className={styles.profileRow}>
                        <span className={styles.profileLabel}>Organization</span>
                        <span className={styles.profileValue}>{profile.org_name}</span>
                    </div>
                </div>

                <div className={styles.profileCard}>
                    <div className={styles.profileCardTitle}>Document Access</div>
                    {profile.permitted_categories.length === 0 ? (
                        <p className={styles.noCats}>
                            No categories assigned yet. Contact your manager to get access.
                        </p>
                    ) : (
                        <>
                            <p style={{ fontSize: "0.82rem", color: "var(--text-3)", marginBottom: "0.85rem" }}>
                                You can search documents in these categories:
                            </p>
                            <div style={{ display: "flex", flexWrap: "wrap", gap: "0.4rem" }}>
                                {profile.permitted_categories.map(c => (
                                    <span key={c.category_id} className={styles.catChip}>{c.name}</span>
                                ))}
                            </div>
                        </>
                    )}
                </div>

                <div className={styles.profileCard}>
                    <div className={styles.profileCardTitle}>Change Password</div>

                    {pwSuccess && (
                        <div className={styles.pwSuccess}>Password updated successfully.</div>
                    )}
                    {pwError && (
                        <div className={styles.pwError}>{pwError}</div>
                    )}

                    <div className={styles.profileRow}>
                        <span className={styles.profileLabel}>Current Password</span>
                        <input
                            className={styles.pwInput}
                            type="password"
                            placeholder="••••••••"
                            value={currentPw}
                            onChange={e => setCurrentPw(e.target.value)}
                            autoComplete="current-password"
                        />
                    </div>
                    <div className={styles.profileRow}>
                        <span className={styles.profileLabel}>New Password</span>
                        <input
                            className={styles.pwInput}
                            type="password"
                            placeholder="At least 8 characters"
                            value={newPw}
                            onChange={e => setNewPw(e.target.value)}
                            autoComplete="new-password"
                        />
                    </div>
                    <div className={styles.profileRow}>
                        <span className={styles.profileLabel}>Confirm New Password</span>
                        <input
                            className={styles.pwInput}
                            type="password"
                            placeholder="Repeat new password"
                            value={confirmPw}
                            onChange={e => setConfirmPw(e.target.value)}
                            autoComplete="new-password"
                        />
                    </div>
                    <button
                        className={styles.pwBtn}
                        onClick={changePassword}
                        disabled={changePw.isPending}
                    >
                        {changePw.isPending ? "Saving…" : "Update Password"}
                    </button>
                </div>
            </div>
        </div>
    );
};

// ── My Court Assignments — associate dispatch ───────────────────────────────

const HEARING_OUTCOMES = ["Heard", "Adjourned", "Partially Heard", "Reserved for Judgment", "Dismissed", "Withdrawn", "ex-parte"];

const AssignmentsPanel = ({ userId }: { userId: string }) => {
    const today = new Date().toISOString().slice(0, 10);
    const { data: hearings = [], isLoading } = useMyHearings(userId, today);
    const updateOutcome = useUpdateHearingOutcome(userId, today);
    const [editingId, setEditingId] = useState<string | null>(null);
    const [outcome,   setOutcome]   = useState("");
    const [adjReason, setAdjReason] = useState("");
    const [saveErr,   setSaveErr]   = useState("");

    const startMarking = (h: AssignedHearing) => {
        setEditingId(h.hearing_id);
        setOutcome(h.hearing_outcome ?? "");
        setAdjReason(h.adj_reason ?? "");
        setSaveErr("");
    };

    const saveOutcome = (hearingId: string) => {
        if (!outcome) { setSaveErr("Select an outcome first."); return; }
        setSaveErr("");
        updateOutcome.mutate({ hearingId, payload: { hearing_outcome: outcome, adj_reason: adjReason || undefined } }, {
            onSuccess: () => setEditingId(null),
            onError: (e: Error) => setSaveErr(e.message || "Could not save."),
        });
    };

    if (isLoading) return <div className={styles.panelContent}><div className={styles.loadingWrap}>Loading…</div></div>;

    if (hearings.length === 0) {
        return (
            <div className={styles.panelContent}>
                <div className={styles.emptyDocs}>
                    No court hearings assigned to you right now. When your firm owner dispatches you to a hearing, it'll show up here.
                </div>
            </div>
        );
    }

    return (
        <div className={styles.panelContent}>
            <div style={{ display: "flex", flexDirection: "column", gap: "0.85rem" }}>
                {hearings.map(h => (
                    <div key={h.hearing_id} style={{ background: "var(--bg-1)", border: "1px solid var(--border)", borderRadius: "var(--radius)", padding: "1rem" }}>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "0.5rem" }}>
                            <div>
                                <div style={{ fontWeight: 700, fontSize: "1rem" }}>{h.title}</div>
                                {h.matter_title && <div style={{ color: "var(--text-2)", fontSize: "0.85rem" }}>{h.matter_title}</div>}
                                <div style={{ color: "var(--text-3)", fontSize: "0.82rem", marginTop: "0.25rem" }}>
                                    {h.hearing_date}{h.hearing_time ? ` · ${h.hearing_time}` : ""}
                                    {h.court_name ? ` · ${h.court_name}` : ""}
                                    {h.judge_name ? ` · ${h.judge_name}` : ""}
                                </div>
                            </div>
                            {h.hearing_outcome ? (
                                <span className={styles.statusReady}>{h.hearing_outcome}</span>
                            ) : editingId !== h.hearing_id ? (
                                <button className={styles.sendBtn} style={{ padding: "0.4rem 0.9rem", fontSize: "0.82rem" }} onClick={() => startMarking(h)}>Mark Outcome</button>
                            ) : null}
                        </div>

                        {editingId === h.hearing_id && (
                            <div style={{ marginTop: "0.85rem", paddingTop: "0.85rem", borderTop: "1px solid var(--border)" }}>
                                <select className={styles.pwInput} style={{ width: "100%", marginBottom: "0.6rem" }} value={outcome} onChange={e => setOutcome(e.target.value)}>
                                    <option value="">— Select outcome —</option>
                                    {HEARING_OUTCOMES.map(o => <option key={o}>{o}</option>)}
                                </select>
                                {outcome === "Adjourned" && (
                                    <input className={styles.pwInput} style={{ width: "100%", marginBottom: "0.6rem" }}
                                        placeholder="Adjournment reason (optional)" value={adjReason} onChange={e => setAdjReason(e.target.value)} />
                                )}
                                {saveErr && <div className={styles.pwError} style={{ marginBottom: "0.5rem" }}>{saveErr}</div>}
                                <div style={{ display: "flex", gap: "0.5rem" }}>
                                    <button className={styles.sendBtn} disabled={updateOutcome.isPending} onClick={() => saveOutcome(h.hearing_id)}>
                                        {updateOutcome.isPending ? "Saving…" : "✓ Save — notifies owner & client"}
                                    </button>
                                    <button className={styles.pwBtn} style={{ background: "transparent" }} onClick={() => setEditingId(null)} disabled={updateOutcome.isPending}>Cancel</button>
                                </div>
                            </div>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

// ── Shell ─────────────────────────────────────────────────────────────────────

const NAV: { id: Panel; icon: string; label: string }[] = [
    { id: "chat",        icon: "Q", label: "Ask a Question"       },
    { id: "documents",   icon: "D", label: "My Documents"         },
    { id: "assignments", icon: "⚖", label: "My Court Assignments" },
    { id: "profile",     icon: "P", label: "Profile"              },
];

const PANEL_TITLES: Record<Panel, string> = {
    chat:        "Ask a Question",
    documents:   "My Documents",
    assignments: "My Court Assignments",
    profile:     "My Profile",
};

const PANEL_SUBS: Record<Panel, string> = {
    chat:        "Search and query your firm's documents using AI",
    documents:   "Documents you have access to",
    assignments: "Hearings your firm has dispatched you to attend",
    profile:     "Your account and access permissions",
};

const EmployeePortal = () => {
    const [panel, setPanel] = useState<Panel>("chat");
    const { data: profile, isLoading: profileLoading } = useMyProfile();
    const { data: docs = [], isLoading: docsLoading } = useMyDocuments();
    const logoutMut = useLogout();

    const signOut = () => {
        logoutMut.mutate();
        sessionStorage.clear();
        window.location.hash = "/";
    };

    if (profileLoading || docsLoading) {
        return <div className={styles.loadingWrap}>Loading…</div>;
    }

    const orgName    = profile?.org_name ?? "Your Organization";
    const userName   = profile?.name ?? "Employee";
    const categories = profile?.permitted_categories ?? [];

    return (
        <div className={styles.shell}>
            {/* Sidebar */}
            <aside className={styles.sidebar}>
                <div className={styles.sidebarLogo}>
                    Project<span className={styles.logoAccent}> Ease</span>
                </div>

                <div className={styles.orgBadge}>
                    <div className={styles.orgBadgeName}>{orgName}</div>
                    <div className={styles.orgBadgeRole}>Employee</div>
                </div>

                {categories.length > 0 && (
                    <div className={styles.catList}>
                        <div className={styles.catListLabel}>My Access</div>
                        {categories.map(c => (
                            <span key={c.category_id} className={styles.catChip}>{c.name}</span>
                        ))}
                    </div>
                )}

                <nav className={styles.nav}>
                    <div className={styles.navDivider} />
                    {NAV.map(({ id, icon, label }) => (
                        <button
                            key={id}
                            className={`${styles.navItem} ${panel === id ? styles.navItemActive : ""}`}
                            onClick={() => setPanel(id)}
                        >
                            <span className={styles.navIconBox}>{icon}</span>
                            {label}
                        </button>
                    ))}
                </nav>

                <div className={styles.sidebarFooter}>
                    <div className={styles.sidebarUserName}>{userName}</div>
                    <div className={styles.sidebarUserRole}>Employee</div>
                    <button className={styles.signOutBtn} onClick={signOut}>Sign Out</button>
                </div>
            </aside>

            {/* Main */}
            <div className={styles.main}>
                <header className={styles.header}>
                    <div>
                        <h1 className={styles.headerTitle}>{PANEL_TITLES[panel]}</h1>
                        <p className={styles.headerSub}>{PANEL_SUBS[panel]}</p>
                    </div>
                    <ThemeToggle />
                </header>

                {panel === "chat"        && <ChatPanel orgName={orgName} categories={categories} />}
                {panel === "documents"   && <DocumentsPanel docs={docs} />}
                {panel === "assignments" && profile && <AssignmentsPanel userId={profile.user_id} />}
                {panel === "profile"     && profile && <ProfilePanel profile={profile} />}
            </div>
        </div>
    );
};

export default EmployeePortal;
